# Generated by Django 2.0.2 on 2018-02-11 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FSJUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('ccid', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Adjudicator',
            fields=[
                ('fsjuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FSJ.FSJUser')),
            ],
            bases=('FSJ.fsjuser',),
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('fsjuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FSJ.FSJUser')),
            ],
            bases=('FSJ.fsjuser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('fsjuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FSJ.FSJUser')),
                ('program', models.CharField(max_length=50)),
            ],
            bases=('FSJ.fsjuser',),
        ),
    ]
