# Generated by Django 2.0.2 on 2018-02-20 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FSJUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccid', models.CharField(max_length=255, unique=True, verbose_name='CCID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('userid', models.IntegerField()),
                ('lang_pref', models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', max_length=2, verbose_name='Language Preference')),
            ],
        ),
        migrations.CreateModel(
            name='Adjudicator',
            fields=[
                ('fsjuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FSJ.FSJUser')),
            ],
            bases=('FSJ.fsjuser',),
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('fsjuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FSJ.FSJUser')),
            ],
            bases=('FSJ.fsjuser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('fsjuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FSJ.FSJUser')),
                ('program', models.CharField(max_length=255, verbose_name='Program')),
                ('year', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')], default=1, verbose_name='Year of Study')),
            ],
            bases=('FSJ.fsjuser',),
        ),
    ]
