# Generated by Django 2.0.2 on 2018-02-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSJ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.TextField(verbose_name='Award Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('value', models.PositiveIntegerField(verbose_name='Value')),
                ('programs', models.TextField(verbose_name='Programs')),
                ('years_of_study', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')], verbose_name='Years of Study')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('documents_needed', models.BooleanField(verbose_name='Documents Required')),
                ('is_active', models.BooleanField(verbose_name='Is Active')),
            ],
        ),
    ]
