# Generated by Django 2.0.2 on 2018-03-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSJ', '0002_auto_20180309_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
