# Generated by Django 2.0.2 on 2018-02-25 03:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FSJ', '0002_award'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='id',
        ),
        migrations.AddField(
            model_name='award',
            name='awardid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
