# Generated by Django 2.0.2 on 2018-03-14 03:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FSJ', '0002_auto_20180313_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_submitted', models.BooleanField(verbose_name='Is Submitted')),
                ('application_file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Application Document')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='FSJ.Award', verbose_name='Award')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='FSJ.FSJUser', to_field='ccid', verbose_name='Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='committee',
            name='adjudicators',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='awards',
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
    ]
