# Generated by Django 2.0.2 on 2018-03-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSJ', '0002_auto_20180308_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsjuser',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fsjuser',
            name='ccid',
            field=models.CharField(max_length=255, unique=True, verbose_name='CCID'),
        ),
    ]
