from .forms_student import *
from .forms_adjudicator import *
from .forms_coordinator import *
from .forms_award import *
from .forms_yearofstudy import *
from .forms_committee import *
from .forms_program import ProgramForm
from .forms_application import *
from .forms_fileupload import *
from .forms_comment import *
from .forms_signup import *
from .forms_ranking import *
from .forms_datechange import *